theme[main_bg]="#080A0D"
theme[main_fg]="#E6E6E6"
theme[title]="#FFD700"
theme[hi_fg]="#FF1E32"
theme[selected_bg]="#351017"
theme[selected_fg]="#FFFFFF"
theme[inactive_fg]="#626A73"
theme[proc_misc]="#00D9FF"

theme[cpu_box]="#FF1E32"
theme[mem_box]="#00D9FF"
theme[net_box]="#FFD700"
theme[proc_box]="#FF1E32"
theme[div_line]="#252A30"

theme[temp_start]="#55FF88"
theme[temp_mid]="#FFD700"
theme[temp_end]="#FF1E32"

theme[cpu_start]="#55FF88"
theme[cpu_mid]="#FFD700"
theme[cpu_end]="#FF1E32"

theme[free_start]="#00D9FF"
theme[free_mid]="#00B8FF"
theme[free_end]="#4DCAFF"

theme[cached_start]="#FF3CAC"
theme[cached_mid]="#FF75C8"
theme[cached_end]="#FF3CAC"

theme[available_start]="#55FF88"
theme[available_mid]="#7AFFA7"
theme[available_end]="#55FF88"

theme[used_start]="#FF1E32"
theme[used_mid]="#FF4A59"
theme[used_end]="#FF1E32"

theme[download_start]="#00B8FF"
theme[download_mid]="#00D9FF"
theme[download_end]="#66E7FF"

theme[upload_start]="#FFD700"
theme[upload_mid]="#FFE766"
theme[upload_end]="#FFD700"
