background = #080A0D
foreground = #E6E6E6

cursor-color = #FFD700
selection-background = #351017
selection-foreground = #FFFFFF

palette = 0=#080A0D
palette = 1=#FF1E32
palette = 2=#55FF88
palette = 3=#FFD700
palette = 4=#00B8FF
palette = 5=#FF3CAC
palette = 6=#00D9FF
palette = 7=#E6E6E6

palette = 8=#626A73
palette = 9=#FF4A59
palette = 10=#7AFFA7
palette = 11=#FFE766
palette = 12=#4DCAFF
palette = 13=#FF75C8
palette = 14=#66E7FF
palette = 15=#FFFFFF
