# ============================================
# STARK INDUSTRIES - HYPRLAND
# ============================================

general {
    col.active_border = rgb(FF1E32)
    col.inactive_border = rgb(252A30)
}

decoration {
    shadow {
        color = rgba(FF1E3233)
    }
}
