$color = rgba(8, 10, 13, 1)
$inner_color = rgba(8, 10, 13, 0.72)
$outer_color = rgba(255, 30, 50, 1)
$font_color = rgba(230, 230, 230, 1)
$placeholder_color = rgba(230, 230, 230, 0.7)
$check_color = rgba(0, 217, 255, 1)
