foreground            #E6E6E6
background            #080A0D
cursor                #FFD700
selection_foreground  #FFFFFF
selection_background  #351017

color0  #080A0D
color1  #FF1E32
color2  #55FF88
color3  #FFD700
color4  #00B8FF
color5  #FF3CAC
color6  #00D9FF
color7  #E6E6E6

color8  #626A73
color9  #FF4A59
color10 #7AFFA7
color11 #FFE766
color12 #4DCAFF
color13 #FF75C8
color14 #66E7FF
color15 #FFFFFF
